openapi: 3.0.3

info:
  title: Product API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  /products:
    post:
      operationId: createProduct
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'

      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{product_id}:
    get:
      operationId: getProduct
      summary: Get a product
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

        '404':
          description: Product not found

components:

  schemas:

    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

    CreateProductRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
